name: Test Suite

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  test-suite:
    uses: kubeadapt/actions/.github/workflows/golang-cli-test-suite.yml@main
    with:
      go_version: '1.26.x'
